server:
  port: 8084
  servlet:
    context-path: '/ead-notification/'

spring:
  application:
    name: ead-notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-notification-v2
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-conextual-creation: true
    properties:
      hibernate:
        show_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost